import React, { useState } from 'react';

const FAQS = [
  {
    q: 'What is Agentic SOC Copilot?',
    a: "An AI-powered Security Operations Center platform for banking, built with 6 autonomous AI agents that monitor Azure AD, CrowdStrike, SentinelOne, Palo Alto NGFW, Cisco Duo, and Okta in real time. Developed for FinSpark'26 hackathon.",
  },
  {
    q: 'How does the AI chat work?',
    a: "The SOC Copilot uses Google Gemini 1.5 Flash with a banking security system prompt. It has access to live event counts and risk scores from the backend. Add your GEMINI_API_KEY to .env to enable live AI. Without a key, intelligent fallback responses are provided.",
  },
  {
    q: 'What does "Run Detection Cycle" do?',
    a: 'It triggers all 6 AI agents simultaneously to scan their data sources, generate new telemetry events, score risks, and surface threats. Each cycle generates ~5 new events and updates dashboard statistics.',
  },
  {
    q: 'How does the risk score work?',
    a: 'Each event is scored 0-100 by AI analysis of behavioral patterns, threat intelligence, and context. Critical = 85-100, High = 60-84, Medium = 35-59, Low = 10-34. The dashboard shows the average across all recent events.',
  },
  {
    q: 'Is this connected to real data?',
    a: 'The frontend uses realistic mock data generated by an AI-calibrated simulation engine. The backend API is production-ready and designed for real connector integration. The WebSocket streams live events every 8 seconds when the backend is running.',
  },
  {
    q: 'How do I start the full backend?',
    a: "Install Python deps: pip install -r backend/requirements.txt. Add GEMINI_API_KEY to .env. Run: cd backend, then python -m uvicorn app.main:app --reload --port 8000. API docs at http://localhost:8000/docs.",
  },
];

const SHORTCUTS = [
  { key: 'Click event row', action: 'Open event detail modal with AI analysis' },
  { key: 'Run Cycle button', action: 'Trigger all 6 AI agents for fresh scan' },
  { key: 'Sidebar nav', action: 'Switch between Dashboard, Alerts, Agents, Analytics, Threat Hunt, Investigations, Settings' },
  { key: 'Timeline / Chart toggle', action: 'Switch event feed view mode' },
  { key: 'Severity filter (Alerts page)', action: 'Filter by Critical / High / Medium / Low' },
  { key: 'Quick hunt queries', action: 'Pre-built threat hunt searches' },
];

const AGENTS = [
  { icon: '🧠', name: 'SOC Coordinator', desc: 'Orchestrates all agents, generates AI summaries' },
  { icon: '🔑', name: 'IAM Agent',        desc: 'Azure AD / Okta — identity & MFA monitoring' },
  { icon: '💻', name: 'EDR Agent',         desc: 'CrowdStrike / SentinelOne — endpoint threats' },
  { icon: '🌐', name: 'Network Agent',     desc: 'Palo Alto NGFW — traffic & lateral movement' },
  { icon: '🛡️', name: 'Firewall Agent',  desc: 'Perimeter security & policy violations' },
  { icon: '🔐', name: 'PAM Agent',         desc: 'Cisco Duo / CyberArk — privileged access' },
];

export const Help: React.FC = () => {
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  return (
    <div className="main-content">
      <div style={{ marginBottom: 4 }}>
        <h1 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-primary)' }}>❓ Help & Documentation</h1>
        <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: 2 }}>
          Agentic SOC Copilot — FinSpark&apos;26 Banking Hackathon Project
        </p>
      </div>

      {/* Hero Banner */}
      <div
        className="card-glass"
        style={{ background: 'linear-gradient(135deg, rgba(0,200,255,0.08), rgba(108,99,255,0.08))', borderColor: 'var(--border-active)', padding: '2rem' }}
      >
        <div style={{ display: 'flex', gap: 20, alignItems: 'center', flexWrap: 'wrap' }}>
          <div style={{ fontSize: '3rem' }}>🛡️</div>
          <div>
            <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--cyan)', marginBottom: 6 }}>
              Agentic SOC Copilot
            </h2>
            <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: 1.6, maxWidth: 600 }}>
              An AI-powered Security Operations Center for Indian banking, built with 6 autonomous AI agents,
              Google Gemini integration, real-time WebSocket streaming, and a full React + FastAPI stack.
              Built for the FinSpark&apos;26 Hackathon.
            </p>
          </div>
          <div style={{ marginLeft: 'auto', display: 'flex', flexDirection: 'column', gap: 6 }}>
            <a
              href="http://localhost:8000/docs"
              target="_blank"
              rel="noopener noreferrer"
              className="btn btn--primary"
              style={{ fontSize: '0.8rem', textDecoration: 'none' }}
            >
              API Docs &rarr;
            </a>
            <a
              href="https://github.com/Dayanithi07/Agentic-SOC-Banking"
              target="_blank"
              rel="noopener noreferrer"
              className="btn btn--ghost"
              style={{ fontSize: '0.8rem', textDecoration: 'none', textAlign: 'center' }}
            >
              GitHub &rarr;
            </a>
          </div>
        </div>
      </div>

      <div className="grid-2">
        {/* Agent Reference */}
        <div className="card">
          <div className="section-head"><h2>AI Agents Reference</h2></div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {AGENTS.map(a => (
              <div key={a.name} style={{ display: 'flex', gap: 12, alignItems: 'center', padding: '8px 10px', borderRadius: 8, background: 'var(--bg-secondary)' }}>
                <span style={{ fontSize: '1.2rem' }}>{a.icon}</span>
                <div>
                  <div style={{ fontSize: '0.83rem', fontWeight: 600, color: 'var(--text-primary)' }}>{a.name}</div>
                  <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>{a.desc}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Keyboard / UI shortcuts */}
        <div className="card">
          <div className="section-head"><h2>UI Reference</h2></div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {SHORTCUTS.map(s => (
              <div key={s.key} style={{ display: 'flex', gap: 10, padding: '6px 0', borderBottom: '1px solid var(--border)' }}>
                <span style={{ fontSize: '0.72rem', fontFamily: 'var(--font-mono)', background: 'var(--bg-secondary)', color: 'var(--cyan)', padding: '2px 8px', borderRadius: 4, flexShrink: 0, alignSelf: 'flex-start', whiteSpace: 'nowrap' }}>
                  {s.key}
                </span>
                <span style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', lineHeight: 1.4 }}>{s.action}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* API Reference */}
      <div className="card">
        <div className="section-head"><h2>Backend API Endpoints</h2></div>
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.82rem' }}>
            <thead>
              <tr style={{ borderBottom: '2px solid var(--border)' }}>
                {['Method', 'Endpoint', 'Description'].map(h => (
                  <th key={h} style={{ textAlign: 'left', padding: '8px 12px', color: 'var(--text-muted)', fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {[
                ['GET',  '/api/events',         'Get all security events (paginated)'],
                ['GET',  '/api/events/stats',   'Dashboard statistics (total, critical, avg risk)'],
                ['POST', '/api/run-cycle',      'Trigger AI agent detection cycle'],
                ['POST', '/api/chat',           'SOC Copilot chat (Gemini AI)'],
                ['GET',  '/api/agents/status',  'All 6 agent statuses and event counts'],
                ['WS',   '/ws/telemetry',       'WebSocket live event stream (every 8s)'],
                ['GET',  '/health',             'Health check endpoint'],
                ['GET',  '/docs',               'Interactive Swagger API documentation'],
              ].map(([m, path, desc]) => (
                <tr key={path} style={{ borderBottom: '1px solid var(--border)' }}>
                  <td style={{ padding: '8px 12px' }}>
                    <span style={{
                      fontFamily: 'var(--font-mono)', fontSize: '0.72rem', fontWeight: 700, padding: '2px 6px', borderRadius: 3,
                      background: m === 'GET' ? 'rgba(0,229,176,0.1)' : m === 'POST' ? 'rgba(108,99,255,0.1)' : m === 'WS' ? 'rgba(0,200,255,0.1)' : 'rgba(255,140,66,0.1)',
                      color: m === 'GET' ? 'var(--teal)' : m === 'POST' ? 'var(--indigo)' : m === 'WS' ? 'var(--cyan)' : 'var(--high)',
                    }}>{m}</span>
                  </td>
                  <td style={{ padding: '8px 12px', fontFamily: 'var(--font-mono)', fontSize: '0.78rem', color: 'var(--text-primary)' }}>{path}</td>
                  <td style={{ padding: '8px 12px', color: 'var(--text-secondary)' }}>{desc}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* FAQ Accordion */}
      <div className="card">
        <div className="section-head"><h2>Frequently Asked Questions</h2></div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          {FAQS.map((faq, i) => (
            <div
              key={i}
              style={{ borderRadius: 8, overflow: 'hidden', border: '1px solid var(--border)' }}
            >
              <div
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
                style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', cursor: 'pointer', background: openFaq === i ? 'var(--cyan-dim)' : 'var(--bg-secondary)', transition: 'background 0.2s' }}
              >
                <span style={{ fontSize: '0.85rem', fontWeight: 600, color: openFaq === i ? 'var(--cyan)' : 'var(--text-primary)' }}>{faq.q}</span>
                <span style={{ color: 'var(--text-muted)', transition: 'transform 0.2s', transform: openFaq === i ? 'rotate(180deg)' : 'none' }}>▼</span>
              </div>
              {openFaq === i && (
                <div style={{ padding: '12px 16px', background: 'var(--bg-card)', fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Tech Stack */}
      <div className="card">
        <div className="section-head"><h2>Tech Stack</h2></div>
        <div className="grid-3">
          {[
            { icon: '⚛️', name: 'React 18 + TypeScript', desc: 'Frontend framework' },
            { icon: '⚡', name: 'Vite 5',               desc: 'Build tool & dev server' },
            { icon: '🐍', name: 'FastAPI',               desc: 'Python async backend' },
            { icon: '🤖', name: 'Gemini 1.5 Flash',     desc: 'AI threat analysis' },
            { icon: '🔌', name: 'WebSockets',            desc: 'Real-time streaming' },
            { icon: '🐳', name: 'Docker',                desc: 'Container deployment' },
          ].map(t => (
            <div key={t.name} style={{ display: 'flex', gap: 10, alignItems: 'center', padding: '10px 12px', borderRadius: 8, background: 'var(--bg-secondary)', border: '1px solid var(--border)' }}>
              <span style={{ fontSize: '1.3rem' }}>{t.icon}</span>
              <div>
                <div style={{ fontSize: '0.82rem', fontWeight: 600, color: 'var(--text-primary)' }}>{t.name}</div>
                <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>{t.desc}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
