import React, { useState, useEffect } from 'react';

export const Investigations: React.FC = () => {
  const [incidents, setIncidents] = useState<any[]>([]);

  useEffect(() => {
    const fetchIncidents = async () => {
      try {
        const res = await fetch('http://localhost:8000/api/incidents');
        if (res.ok) {
          setIncidents(await res.json());
        }
      } catch (e) {
        console.error(e);
      }
    };
    fetchIncidents();
    const interval = setInterval(fetchIncidents, 3000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="main-content">
      <div style={{ marginBottom: 16 }}>
        <h1 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-primary)' }}>📋 Investigations</h1>
        <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: 2 }}>
          Security incidents generated by the Investigation Agent based on runtime telemetry and vulnerabilities.
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        {incidents.map((inc, i) => (
          <div key={i} className="card" style={{ borderLeft: '4px solid var(--critical)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <h2 style={{ fontSize: '1.1rem', color: 'var(--text-primary)', marginBottom: 8 }}>{inc.title}</h2>
              <span style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--critical)' }}>Risk: {inc.risk_score} / 100</span>
            </div>
            
            <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: 12 }}>
              <strong>AI Summary:</strong> {inc.summary}
            </div>

            <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: 12 }}>
              <strong>Mitigation Recommendation:</strong><br />
              {inc.recommendation}
            </div>
            
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
              Status: {inc.status.toUpperCase()} &bull; Created: {new Date(inc.created_at).toLocaleString()}
            </div>
          </div>
        ))}
        {incidents.length === 0 && (
          <div className="card" style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-muted)' }}>
            No investigations currently open. Run telemetry replay to generate incidents.
          </div>
        )}
      </div>
    </div>
  );
};

export default Investigations;
